server:
  servlet:
    context-path: /master
  port: 9999

spring:
  application:
    name: master
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5432/master
    username: 'wandern'
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false


kafka:
  topic:
    node-metrics: node-metrics-topic
  group:
    id: node-metrics-group

#  flyway:
#    baseline-on-migrate: true