server:
  servlet:
    context-path: /master
  port: 8080

spring:
  application:
    name: master
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5432/master
    username: 'wandern'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false