server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /ctx
spring:
  application:
    name: agent
  kafka:
    bootstrap-servers: localhost:9092

master:
  url: http://192.168.100.2:9999
  registration:
    retry:
      interval: 30000

healthcheck:
  interval: 10

liveness:
  probe:
    interval: 30000

metrics:
  collection:
    interval:
      seconds: 10

deployment:
  prefix: mragent
