server:
  port: 8081
  servlet:
    context-path: /ctx
spring:
  application:
    name: agent

master:
  url: http://192.168.16.1:9999
  registration:
    retry:
      interval: 15

healthcheck:
  interval: 10

metrics:
  collection:
    interval:
      seconds: 10

deployment:
  prefix: mragent

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
