server:
  port: 8081
  servlet:
    context-path: /ctx
spring:
  application:
    name: agent

master:
  service:
    url: http://localhost:8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
