server:
  port: 8081
  servlet:
    context-path: /ctx
spring:
  application:
    name: agent

master:
  service:
    url: http://localhost:8080

healthcheck:
  interval: 30

metrics:
  collection:
    interval:
      seconds: 30

deployment:
  prefix: mragent

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
